# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163eKPnaSzkIlvOTl3v9OSduCc_YfiBN6
"""

import json
import pickle
import time
import numpy as np
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import regexp_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
import matplotlib.pyplot as plt
import pandas as pd

import sklearn
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error
from sklearn.neighbors import NearestNeighbors
from sklearn import neighbors
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier


import scipy
from nltk.stem import WordNetLemmatizer
from nltk.corpus import sentiwordnet as swn
from nltk.corpus import wordnet as wn


import csv
import os
import pandas as pd
import sys