# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3N8MC7M2vGt8GtEsO6Q-VJzPpdrzjhi
"""
from requirements import *

def autolabel(rects):
    """Attach a text label above each bar in *rects*, displaying its height."""
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{}'.format(height),
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')
def create_plot(labels, male_means, female_means, title, flag, size, save):
  x = np.arange(len(labels))  # the label locations
  width = 0.35  # the width of the bars

  fig, ax = plt.subplots()
  fig.set_size_inches(size, size)
  rects1 = ax.bar(x - width/2, male_means, width, label='Male')
  rects2 = ax.bar(x + width/2, female_means, width, label='Female')

# Add some text for labels, title and custom x-axis tick labels, etc.
  ax.set_ylabel('Scores')
  ax.set_title(title)
  ax.set_xticks(x)
  ax.set_xticklabels(labels)
  ax.legend()

  if flag == 1:
    autolabel(rects1)
    autolabel(rects2)

  if save == 1:
    fig.savefig('test2png.png', dpi=100)

  fig.tight_layout()

  plt.show()

def sparse_plot(A):
  plt.spy(A)
